
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sockeye
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "1"
    spec:
      containers:
        - image: gcr.io/fit-stream-305821/sockeye-e92784dbbc40447852d8e5fa42eed6b4@sha256:ca41e1fc1a43fa904dfe67743ea31b70ab5a15b03ca21669ffe59f252e961901
          env:
            - name: CLUSTER_NAME
              value: arn:aws:eks:eu-central-1:043455440429:cluster/staging
            - name: NAMESPACE
              value: midimansland

---
