apiVersion: v1
kind: ServiceAccount
metadata:
  name: sockeye
  namespace: <namespace>
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sockeye
  namespace: <namespace>
rules:
  - apiGroups:
      - serving.knative.dev
    resources:
      - services
      - routes
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sockeye
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sockeye
subjects:
  - kind: ServiceAccount
    name: sockeye
    namespace: <namespace>
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sockeye
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "1"
    spec:
      serviceAccountName: sockeye
      containers:
        - image: ko://github.com/n3wscott/sockeye/cmd/sockeye
          env:
            - name: CLUSTER_NAME
              value: <clustername>